name: Lint
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.7
          args: --timeout 6m0s --verbose -- ./...
          only-new-issues: true
